import { StyleSheet, View } from 'react-native';
import React from 'react';

const PostScreen = () => {
  return (
    <View style={styles.container}> </View>
  )
}

export default PostScreen;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white'
  }
})

/**
 * NAPHTALI DO NOT DELETE THIS FILE IT'S IMPORTANT
 * NAPHTALI DO NOT DELETE THIS FILE IT'S IMPORTANT
 * NAPHTALI DO NOT DELETE THIS FILE IT'S IMPORTANT
 * NAPHTALI DO NOT DELETE THIS FILE IT'S IMPORTANT
 * NAPHTALI DO NOT DELETE THIS FILE IT'S IMPORTANT
 * NAPHTALI DO NOT DELETE THIS FILE IT'S IMPORTANT
 * NAPHTALI DO NOT DELETE THIS FILE IT'S IMPORTANT
 * NAPHTALI DO NOT DELETE THIS FILE IT'S IMPORTANT
 * NAPHTALI DO NOT DELETE THIS FILE IT'S IMPORTANT
 * NAPHTALI DO NOT DELETE THIS FILE IT'S IMPORTANT
 * NAPHTALI DO NOT DELETE THIS FILE IT'S IMPORTANT
 * NAPHTALI DO NOT DELETE THIS FILE IT'S IMPORTANT
 */